# Generated by Django 4.2 on 2025-10-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
