# Generated by Django 4.2 on 2025-10-03 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='is_sale',
        ),
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
        migrations.RemoveField(
            model_name='food',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='restorant',
            name='meno',
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restorant',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price', models.PositiveIntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('restorant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='food.restorant')),
            ],
            options={
                'unique_together': {('food', 'restorant')},
            },
        ),
        migrations.AddField(
            model_name='restorant',
            name='foods',
            field=models.ManyToManyField(through='food.MenuItem', to='food.food'),
        ),
    ]
