# Generated by Django 4.2 on 2025-10-03 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_food_is_sale_remove_food_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorant',
            name='star',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
