# Generated by Django 4.2 on 2025-10-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_restorant_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meno_foods', to='food.food'),
        ),
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_order', to='food.food'),
        ),
        migrations.AlterField(
            model_name='order',
            name='res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_order', to='food.restorant'),
        ),
    ]
