# Generated by Django 4.2 on 2025-10-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_menuitem_food_alter_order_food_alter_order_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likes', to='food.restorant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('SHIPPED', 'ارسال شده'), ('DELIVERED', 'تحویل داده شده')], default='PENDING', max_length=100),
        ),
    ]
